server:
  port: 9000
logging:
  level:
    org.springframework.security: TRACE
    com.zaxxer.hikari: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
spring:
  application:
    name: oauth-server
  datasource:
    url: jdbc:mysql://localhost:3306/tiny_web?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Tianye0903.
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5 # HikariCP 连接池最小空闲连接数，默认10
      maximum-pool-size: 20 # HikariCP 连接池最大连接数，默认10
      idle-timeout: 30000 # HikariCP 连接池中连接最大空闲时间（毫秒），默认600000（10分钟）
      pool-name: HikariCP # HikariCP 连接池名称，默认HikariPool-1
      max-lifetime: 1800000 # HikariCP 连接的最大存活时间（毫秒），默认1800000（30分钟）
      connection-timeout: 30000 # HikariCP 获取连接的最大等待时间（毫秒），默认30000（30秒）
      auto-commit: true # HikariCP 是否自动提交，默认true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update # JPA 自动建表策略，update为自动更新表结构
    show-sql: true # 是否显示SQL语句，开发时建议开启
    properties:
      hibernate:
        format_sql: true
authentication:
  jwt:
    public-key-path: classpath:keys/public.pem
    private-key-path: classpath:keys/private.pem

  clients:
    - client-id: oidc-client
      client-secret: secret
      authentication-methods:
        - client_secret_basic
      grant-types:
        - authorization_code
        - refresh_token
      redirect-uris:
        - http://localhost:9000/
      post-logout-redirect-uris:
        - http://127.0.0.1:8080/
      scopes:
        - openid
        - profile
      client-setting:
        require-authorization-consent: true
    - client-id: vue-client
      authentication-methods:
        - none                    # ✅ 表示前端（公有客户端）不需要 client secret
      grant-types:
        - authorization_code      # ✅ 标准 OIDC 授权码流程
        - refresh_token           # ✅ 启用 refresh_token 支持
      redirect-uris:
        - http://localhost:5173/callback
        - http://localhost:5173/silent-renew.html # silent renew 时用于隐式授权流程的 iframe 回调页面。
      post-logout-redirect-uris:
        - http://127.0.0.1:8080/
      scopes:
        - openid
        - profile
        - offline_access          # ✅ 必须启用，否则不会发 refresh_token
      client-setting:
        require-authorization-consent: false
        require-proof-key: true    # 开启 PKCE，是 Authorization Code Flow 安全的关键部分，前端用 code_challenge 和 code_verifier 实现。